import { Exo_2 } from 'next/font/google'
import Header from './components/Header';
import "./globals.css";
import Footer from './components/Footer';

const exo2 = Exo_2({
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo2.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
